THUNK_LIST_TOOLCHAIN_WIN32 = {
  '3.9999+4.10': {
    'kernel32': [
      'CancelIo',
      'CreateWaitableTimerA',
      'MultiByteToWideChar',
      'SetWaitableTimer',
      'SwitchToThread',
      'WideCharToMultiByte',
    ]
  },
  '4.0': {
    'kernel32': [
      'CopyFileExA',
      'CopyFileExW',
      'CopyFileW',
      'CreateDirectoryW',
      'CreateEventW',
      'CreateProcessW',
      'CreateSemaphoreW',
      'CreateThread',
      'CreateWaitableTimerW',
      'GetEnvironmentVariableW',
      'GetModuleFileNameW',
      'GetTempPathW',
      'LockFileEx',
      'ReadDirectoryChangesW',
      'SetCurrentDirectoryW',
      'SetEnvironmentVariableW',
      'SetHandleInformation',
      'UnlockFileEx',
    ],
    'shell32': [
      'CommandLineToArgvW',
    ],
  },
  '5.0': {
    'advapi32': [
      'ConvertStringSecurityDescriptorToSecurityDescriptorW',
    ],
    'kernel32': [
      'CreateToolhelp32Snapshot',
      'GetCPInfoExA',
      'GetLongPathNameW',
      'GetVolumePathNameW',
      'GlobalMemoryStatusEx',
      'Module32First',
      'Module32Next',
      'OpenThread',
      'SetFilePointerEx',
    ],
  },
  '5.1': {
    'kernel32': [
      ('AddVectoredExceptionHandler', lambda v_major: v_major >= 12),
      'GetConsoleProcessList',
      'GetModuleHandleExW',
      'GetNumaHighestNodeNumber',
      'GetNumaNodeProcessorMask',
      'GetSystemTimes',
      'GetSystemWow64DirectoryA',
      'GetVolumePathNamesForVolumeNameW',
      'LCMapStringW',
      ('RemoveVectoredExceptionHandler', lambda v_major: v_major >= 12),
    ],
    'ws2_32': [
      'freeaddrinfo',
      'getaddrinfo',
      'getnameinfo',
    ],
  },
  '5.2': {
    'advapi32': [
      'RegDeleteKeyExA',
      'RegDeleteKeyExW',
    ],
    'kernel32': [
      'FlsAlloc',
      'FlsFree',
      'FlsGetValue',
      'FlsSetValue',
      'GetCurrentProcessorNumber',
      'GetLargePageMinimum',
      'NeedCurrentDirectoryForExePathA',
      'NeedCurrentDirectoryForExePathW',
      'SetThreadStackGuarantee',
    ],
  },
  '6.0': {
    'bcrypt': [
      'BCryptGenRandom',
    ],
    'kernel32': [
      'CancelIoEx',
      'CompareStringOrdinal',
      'CreateSymbolicLinkA',
      'CreateSymbolicLinkW',
      'CreateWaitableTimerExW',
      'DeleteProcThreadAttributeList',
      'GetFileInformationByHandleEx',
      'GetFinalPathNameByHandleA',
      'GetFinalPathNameByHandleW',
      'GetTickCount64',
      'InitializeProcThreadAttributeList',
      'LCMapStringEx',
      'LocaleNameToLCID',
      'SetFileInformationByHandle',
      'UpdateProcThreadAttribute',
    ],
  },
  '6.1': {
    'kernel32': [
      'GetActiveProcessorCount',
      'GetActiveProcessorGroupCount',
      'GetMaximumProcessorCount',
      'GetMaximumProcessorGroupCount',
      'SetWaitableTimerEx',
    ],
  },
  '6.2': {
    'api-ms-win-core-path-l1-1-0': [
      'PathAllocCanonicalize',
      'PathAllocCombine',
      'PathCchAddBackslash',
      'PathCchAddBackslashEx',
      'PathCchAddExtension',
      'PathCchAppend',
      'PathCchAppendEx',
      'PathCchCanonicalize',
      'PathCchCanonicalizeEx',
      'PathCchCombine',
      'PathCchCombineEx',
      'PathCchFindExtension',
      'PathCchIsRoot',
      'PathCchRemoveBackslash',
      'PathCchRemoveBackslashEx',
      'PathCchRemoveExtension',
      'PathCchRemoveFileSpec',
      'PathCchRenameExtension',
      'PathCchSkipRoot',
      'PathCchStripPrefix',
      'PathCchStripToRoot',
      'PathIsUNCEx',
    ],
    'kernel32': [
      'AddDllDirectory',
      'CopyFile2',
      'GetCurrentThreadStackLimits',
      'GetSystemTimePreciseAsFileTime',
      'RemoveDllDirectory',
    ],
  },
}

THUNK_LIST_TOOLCHAIN_MSVCRT = {
  '5.0': [
    '_ctime64',
    '_findfirst64',
    '_findnext64',
    '_futime64',
    ('_gmtime64', lambda v_major: v_major < 14),
    '_localtime64',
    ('_stat64', lambda v_major: v_major < 13),
    ('_time64', lambda v_major: v_major < 13),
    '_utime64',
    '_wfindfirst64',
    '_wfindnext64',
    '_wutime64',
  ],
  '6.0': [
    '_wputenv_s',
    'wcscat_s',
    'wcscpy_s',
    'wcsncat_s',
    'wcsncpy_s',
    # added in 13 to implement C95 wcstok
    ('wcstok_s', lambda v_major: v_major < 13),
  ],
}
