THUNK_LIST_MSVCRT = {
  '4.0': [
    '_beginthreadex',
    '_wchdir',
    '_wchmod',
    '_wfindfirst',
    '_wfindfirst32',
    '_wfindfirst32i64',
    '_wfindfirsti64',
    '_wfindnext',
    '_wfindnext32',
    '_wfindnext32i64',
    '_wfindnexti64',
    '_wfopen',
    '_wfullpath',
    '_wgetcwd',
    '_wmkdir',
    '_wopen',
    '_wstat32',
    ('_wstat32i64', lambda v_major : v_major >= 12),
    '_wstati64',
    '_wutime',
    '_wutime32',
  ],
  '5.0': [
    '_ctime64',
    '_findfirst64',
    '_findnext64',
    ('_fstat64', lambda v_major: v_major < 13),
    '_futime64',
    ('_gmtime64', lambda v_major: v_major < 14),
    '_localtime64',
    ('_stat64', lambda v_major: v_major < 13),
    ('_time64', lambda v_major: v_major < 13),
    '_utime64',
    '_wfindfirst64',
    '_wfindnext64',
    ('_wstat64', lambda v_major: v_major < 13),
    '_wutime64',
  ],
  '5.1': [
    ('_aligned_free', lambda v_major: v_major < 13),
    ('_aligned_malloc', lambda v_major: v_major < 13),
  ],
  '6.0': [
    '_wputenv_s',
    'wcscat_s',
    'wcscpy_s',
    'wcsncat_s',
    'wcsncpy_s',
    # added in 13 to implement C95 wcstok
    ('wcstok_s', lambda v_major: v_major < 13),
  ],
}
