CC  = gcc
CXX = g++

override CFLAGS   += -std=c23 -O2 -mcrtdll=utf8-ucrt
override CXXFLAGS += -std=c++23 -O2 -mcrtdll=utf8-ucrt -stdlib=libutf8-stdc++
override LDFLAGS  += -mcrtdll=utf8-ucrt -stdlib=libutf8-stdc++

C_TEST_SRCS  = $(filter-out console/util.c,$(wildcard console/*.c))
C_TEST_EXES  = $(patsubst console/%.c,$(DIR)/%.exe,$(C_TEST_SRCS))
C_TEST_NAMES = $(patsubst console/%.c,%,$(C_TEST_SRCS))

CXX_TEST_SRCS  = $(wildcard console/*.cc)
CXX_TEST_EXES  = $(patsubst console/%.cc,$(DIR)/%.exe,$(CXX_TEST_SRCS))
CXX_TEST_NAMES = $(patsubst console/%.cc,%,$(CXX_TEST_SRCS))

all: $(C_TEST_EXES) $(CXX_TEST_EXES)

$(DIR)/util.o: console/util.c
	$(CC) $(CFLAGS) -c $< -o $@

$(DIR)/%.exe: console/%.c $(DIR)/util.o
	$(CC) $(CFLAGS) $(LDFLAGS) $^ -o $@

$(DIR)/%.exe: console/%.cc $(DIR)/util.o
	$(CXX) $(CXXFLAGS) $(LDFLAGS) $^ -o $@

test-%: $(DIR)/%.exe
	@echo ====== [$*] ======
	@$(subst /,\,$(DIR)/$*.exe)

test: $(foreach name,$(C_TEST_NAMES) $(CXX_TEST_NAMES),test-$(name))

clean:
	-del $(C_TEST_EXES) $(CXX_TEST_EXES)
