FROM docker.io/library/alpine:3.23

RUN apk update && \
    apk add \
      autoconf automake build-base cmake flex gettext libtool llvm ninja-build ninja-is-really-ninja texinfo \
      7zip curl file gawk libarchive-tools python3 py3-packaging zstd
