name: Build

on: [push, pull_request]

jobs:
  param:
    name: Determine parameter
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v4

      - id: param
        run: |
          .ci/github-action-param.py --ref-type '${{ github.ref_type }}' --ref-name '${{ github.ref_name }}' >"$GITHUB_OUTPUT"

    outputs:
      branch: ${{ steps.param.outputs.branch }}
      profile: ${{ steps.param.outputs.profile }}
      exclude_profile_branch: ${{ steps.param.outputs.exclude_profile_branch }}
      alt_branch: ${{ steps.param.outputs.alt_branch }}
      alt_profile: ${{ steps.param.outputs.alt_profile }}
      release: ${{ steps.param.outputs.release }}
      prerelease: ${{ steps.param.outputs.prerelease }}
      sat_group: ${{ steps.param.outputs.sat_group }}
      sat_exclude_profile_branch: ${{ steps.param.outputs.sat_exclude_profile_branch }}

  download_source:
    name: Download source
    runs-on: ubuntu-slim
    needs: param
    strategy:
      fail-fast: true
      matrix:
        branch: ${{ fromJson(needs.param.outputs.branch) }}
    steps:
      - uses: actions/checkout@v4

      - uses: ConorMacBride/install-package@v1
        with:
          apt: python3-libarchive-c

      - name: Download source
        run: |
          ./main.py --branch ${{ matrix.branch }} --profile 64-mcf --download-only

      - uses: actions/upload-artifact@v4
        with:
          name: src-${{ matrix.branch }}
          path: |
            assets

  build_container:
    name: Build container
    strategy:
      fail-fast: true
      matrix:
        build_arch: [x86_64, aarch64]
        include:
          - build_arch: x86_64
            runner: ubuntu-24.04
          - build_arch: aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Build container
        run: |
          podman build -t mingw-lite/buildenv support/buildenv

          mkdir assets
          podman save mingw-lite/buildenv:latest | zstd -o assets/buildenv.tar.zst

      - name: Upload container
        uses: actions/upload-artifact@v4
        with:
          name: buildenv-${{ matrix.build_arch }}
          path: assets/buildenv.tar.zst

  build:
    name: Build
    needs: [param, download_source, build_container]
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJson(needs.param.outputs.branch) }}
        profile: ${{ fromJson(needs.param.outputs.profile) }}
        exclude: ${{ fromJson(needs.param.outputs.exclude_profile_branch) }}
    uses: ./.github/workflows/build_single.yml
    with:
      build_arch: x86_64
      runner: ubuntu-24.04
      branch: ${{ matrix.branch }}
      profile: ${{ matrix.profile }}

  alt_build_arm:
    name: Alternative build (ARM)
    needs: [param, download_source, build_container]
    if: ${{ ! fromJson(needs.param.outputs.release) }}
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJson(needs.param.outputs.alt_branch) }}
        profile: ${{ fromJson(needs.param.outputs.alt_profile) }}
    uses: ./.github/workflows/build_single.yml
    with:
      build_arch: aarch64
      runner: ubuntu-24.04-arm
      branch: ${{ matrix.branch }}
      profile: ${{ matrix.profile }}
      upload_prefix: alt_build_arm-

  build_container_wsl:
    name: Build container (WSL)
    needs: [param]
    if: ${{ ! fromJson(needs.param.outputs.release) }}
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4

      - name: Build container (WSL)
        run: |
          Copy-Item -Path support/wsl/.wslconfig -Destination "$env:USERPROFILE/.wslconfig"

          Invoke-WebRequest `
            -Uri https://cdimages.ubuntu.com/ubuntu-wsl/noble/daily-live/current/noble-wsl-amd64.wsl `
            -OutFile noble-wsl-amd64.wsl

          wsl --import mingw-lite-buildenv . noble-wsl-amd64.wsl

          wsl --distribution mingw-lite-buildenv --exec `
            apt update
          wsl --distribution mingw-lite-buildenv --exec `
            env DEBIAN_FRONTEND=noninteractive `
              apt-get install --no-install-recommends -y `
                autoconf automake build-essential cmake flex gettext libtool llvm ninja-build texinfo `
                7zip ca-certificates curl file gawk libarchive-tools python3 python3-libarchive-c python3-packaging zstd

          wsl --distribution mingw-lite-buildenv --exec `
            sync
          wsl --shutdown

          mkdir assets
          wsl --export mingw-lite-buildenv - | zstd -9 -o assets/buildenv.tar.zst

      - uses: actions/upload-artifact@v4
        with:
          name: wsl-buildenv
          path: assets/buildenv.tar.zst

  alt_build_wsl:
    name: Alternative build (WSL)
    needs: [param, download_source, build_container_wsl]
    if: ${{ ! fromJson(needs.param.outputs.release) }}
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJson(needs.param.outputs.alt_branch) }}
        profile: ${{ fromJson(needs.param.outputs.alt_profile) }}
    uses: ./.github/workflows/wsl_build_single.yml
    with:
      branch: ${{ matrix.branch }}
      profile: ${{ matrix.profile }}

  release:
    name: Release
    needs: [param, build]
    if: ${{ fromJson(needs.param.outputs.release) }}
    strategy:
      fail-fast: false
      matrix:
        branch: ${{ fromJson(needs.param.outputs.branch) }}
    runs-on: ubuntu-24.04
    steps:
      - uses: ConorMacBride/install-package@v1
        with:
          apt: 7zip jq libarchive-tools

      - uses: actions/download-artifact@v4
        with:
          pattern: mingw*
          path: dist
          merge-multiple: true

      - name: 7z archive
        run: |
          cd dist
          jobs=$(nproc)

          mingw_list=(
            $(echo '${{ needs.param.outputs.profile }}' | jq -r '.[]')
          )

          for pn in ${mingw_list[@]} ; do
            {
              dn=mingw$pn-${{ matrix.branch }}
              fn=$(ls mingw$pn-*.tar.zst)
              bn=$(basename $fn .tar.zst)
              bsdtar -xf $fn
              7z a -t7z -mx9 -ms=on -m0=LZMA:d=64m:fb64 $bn.7z $dn
              rm -rf $dn
            } &
            while [[ $(jobs -r -p | wc -l) -ge $jobs ]] ; do
              sleep 1
            done
          done
          wait

          for pn in ${mingw_list[@]} ; do
            {
              dn=mingw$pn-${{ matrix.branch }}
              fn=$(ls xmake-mingw$pn-*.tar.zst)
              bn=$(basename $fn .tar.zst)
              bsdtar -xf $fn
              7z a -t7z -mx9 -ms=on -m0=LZMA:d=64m:fb64 $bn.7z $dn
              rm -rf $dn
            } &
            while [[ $(jobs -r -p | wc -l) -ge $jobs ]] ; do
              sleep 1
            done
          done
          wait

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ needs.param.outputs.prerelease }}
          make_latest: 'false'
          files: |
            dist/mingw*.tar.zst
            dist/mingw*.7z
            dist/x-mingw*.tar.zst
            dist/xmake-mingw*.7z

  sat_archive:
    name: Semi-automated test archive (${{ matrix.name }})
    if: ${{ ! fromJson(needs.param.outputs.release) }}
    runs-on: ubuntu-24.04
    needs: [param, build_container, build]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.param.outputs.sat_group) }}
    steps:
      - uses: actions/checkout@v4

      - uses: ConorMacBride/install-package@v1
        with:
          apt: jq libarchive-tools

      - uses: actions/download-artifact@v4
        with:
          pattern: ${{ matrix.pattern }}
          path: dist
          merge-multiple: true

      - run: |
          rm dist/x-mingw*.tar.zst

      - name: Create test archive
        run: |
          branch=(
            $(echo '${{ needs.param.outputs.branch }}' | jq -r '.[]')
          )
          profile=(
            $(echo '${{ matrix.profile }}' | jq -r '.[]')
          )

          mkdir layer
          mkdir pkg

          for b in ${branch[@]} ; do
            for p in ${profile[@]} ; do
              if [[ ":${{ needs.param.outputs.sat_exclude_profile_branch }}:" == *":$p-$b:"* ]] ; then
                continue
              fi
              ./sat.py --branch $b --profile $p
            done
          done

          (
            cd pkg
            7z a -t7z -mx9 -ms=on -mqs -m0=LZMA:d=${{ matrix.dict }}:fb64 ../dist/sat${{ matrix.name }}.7z sat*
          )

      - uses: actions/upload-artifact@v4
        with:
          name: sat${{ matrix.name }}
          path: dist/sat${{ matrix.name }}.7z
