name: Build single (WSL)

on:
  workflow_call:
    inputs:
      build_arch:
        required: true
        type: string
      runner:
        required: true
        type: string
      profile:
        required: true
        type: string
      branch:
        required: true
        type: string
      wsl_version:
        required: true
        type: number

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.runner }}

    steps:
      - name: Configure Git
        run: |
          git config --global core.symlinks true

      - uses: actions/checkout@v6

      - name: Download source
        uses: actions/download-artifact@v8
        with:
          name: src-${{ inputs.branch }}
          path: assets

      - uses: actions/download-artifact@v8
        with:
          name: wsl-buildenv-${{ inputs.build_arch }}
          path: assets

      - uses: ./.github/setup-bsdtar

      - name: Install Python Package
        run: |
          pip install packaging

      - name: Build
        run: |
          Copy-Item -Path .ci/wsl/.wslconfig -Destination "$env:USERPROFILE/.wslconfig"

          zstd -d assets/buildenv.tar.zst -o assets/buildenv.tar
          wsl --import mlenv env assets/buildenv.tar --version ${{ inputs.wsl_version }}
          Remove-Item -Path assets/buildenv.tar , assets/buildenv.tar.zst

          wsl --distribution mlenv --exec `
            ./main.py --branch ${{ inputs.branch }} --profile ${{ inputs.profile }}

          wsl --shutdown
          wsl --unregister mlenv

      - uses: actions/upload-artifact@v7
        with:
          name: alt_build_wsl${{ inputs.wsl_version }}_${{ inputs.build_arch }}-mingw${{ inputs.profile }}-${{ inputs.branch }}
          path: dist

      - name: Test
        timeout-minutes: 15
        run: |
          python test.py --branch ${{ inputs.branch }} --profile ${{ inputs.profile }} --verbose
