name: Build single (WSL)

on:
  workflow_call:
    inputs:
      profile:
        required: true
        type: string
      branch:
        required: true
        type: string
      wsl_version:
        required: true
        type: number

jobs:
  build:
    name: Build
    runs-on: windows-2025

    steps:
      - name: Configure Git
        run: |
          git config --global core.autocrlf false
          git config --global core.symlinks true

      - uses: actions/checkout@v6

      - name: Download source
        uses: actions/download-artifact@v8
        with:
          name: src-${{ inputs.branch }}
          path: assets

      - uses: actions/download-artifact@v8
        with:
          name: wsl-buildenv
          path: assets

      - uses: ./.github/setup-bsdtar

      - name: Install Python Package
        run: |
          pip install packaging

      - name: Build
        run: |
          Copy-Item -Path support/wsl/.wslconfig -Destination "$env:USERPROFILE/.wslconfig"

          zstd -d assets/buildenv.tar.zst -o assets/buildenv.tar
          wsl --import mingw-lite-buildenv . assets/buildenv.tar --version ${{ inputs.wsl_version }}
          Remove-Item -Path assets/buildenv.tar , assets/buildenv.tar.zst

          wsl --distribution mingw-lite-buildenv --exec `
            ./main.py --branch ${{ inputs.branch }} --profile ${{ inputs.profile }}

          wsl --shutdown
          wsl --unregister mingw-lite-buildenv

      - uses: actions/upload-artifact@v7
        with:
          name: alt_build_wsl${{ inputs.wsl_version }}-mingw${{ inputs.profile }}-${{ inputs.branch }}
          path: dist

      - name: Test
        timeout-minutes: 15
        run: |
          python test.py --branch ${{ inputs.branch }} --profile ${{ inputs.profile }} --verbose
